coded lgtm feature
opensourceways/robot-gitee-opengauss-review pull request #2
Opened 2021-11-10 03:19 UTC by xwz123

2021-11-15 08:51 UTC, zengchen1024 requested changes

2021-11-15 08:51 UTC, zengchen1024 commented on lgtm.go
> +	return bot.cli.RemovePRLabel(prInfo.Org, prInfo.Repo, prInfo.Number, removeLabels)
use RemovePRLabels instead

2021-11-15 08:51 UTC, zengchen1024 commented on lgtm.go
> +	if bot.keepLgtmLabelBySha(bConfig, prInfo, log) {
no need this fuction.

2021-11-15 08:51 UTC, zengchen1024 commented on lgtm.go
> +	curLgtmLabels := prCurrentLGTMLabels(prInfo.Labels)
s/curLgtmLabels/v/
s/prCurrentLGTMLabels/getLGTMLabelsOnPR

2021-11-15 08:51 UTC, zengchen1024 commented on robot.go
> +	if prNe.PullRequest == nil || prNe.PullRequest.State != "open" {
use prNe.IsPROpen instead

2021-11-15 08:51 UTC, zengchen1024 commented on lgtm.go
> +func doWhat(comment string) (bool, bool) {
s/doWhat/getActionOfLGTM

2021-11-15 08:51 UTC, zengchen1024 commented on robot.go
> +	v, err = bot.inRepoOwnersFile(commenter, info, "OWNERS", log)
if v, err = bot.inRepoOwnersFile(commenter, info, "OWNERS", log); err != nil || v {
return v, err
}

2021-11-15 09:10 UTC, xwz123 commented on config.go
> +	return sps.Has(repo)
the golangci-lint check the code return sets.NewString(c.SpecialRepo...).Has(repo) report this needs split t

2021-11-15 09:32 UTC, zengchen1024 requested changes

2021-11-15 09:32 UTC, zengchen1024 commented on robot.go
> +	regSigFilePattern := regexp.MustCompile("^sig/[a-zA-Z0-9_-]+/.+")
s/sig/sigs

2021-11-15 09:32 UTC, zengchen1024 commented on robot.go
> +func (bot *robot) inSigDirOwnersFile(
this function is better to use the central repo to get the all the owners file content instead of get them one by one

2021-11-15 09:32 UTC, zengchen1024 commented on robot.go
> +func decodeOwners(content string, log *logrus.Entry) sets.String {
this function has too many blank lines.

2021-11-15 09:32 UTC, zengchen1024 commented on lgtm.go
> +	if labelLenLimit := 20; len(labelLGTM) > labelLenLimit {
declare a constant variable for 20

2021-11-15 09:32 UTC, zengchen1024 commented on lgtm.go
> +	if err := bot.cli.AddMultiPRLabel(prInfo.Org, prInfo.Repo, prInfo.Number, []string{label}); err != nil {
if create label which is unavailable in repo directly, the label's color is white.

2021-11-15 09:42 UTC, xwz123 commented on robot.go
> +	"encoding/base64"
moved the check permissions login  in  permission.go file

2021-11-15 09:46 UTC, xwz123 commented on lgtm.go
> +func doWhat(comment string) (bool, bool) {
this method logic used approve.go too ,and finally we remove this method.

2021-11-15 09:53 UTC, zengchen1024 requested changes

2021-11-15 09:53 UTC, zengchen1024 commented on lgtm.go
> +	return bot.cli.RemovePRLabel(prInfo.Org, prInfo.Repo, prInfo.Number, removeLabels)
use RemovePRLabels instead

2021-11-16 09:31 UTC, zengchen1024 requested changes

2021-11-16 09:31 UTC, zengchen1024 commented on config.go
> +	SpecialRepo []string `json:"special_repo,omitempty"`
no need

2021-11-16 09:32 UTC, zengchen1024 approved these changes
I will do minor optimization for  the codes

2021-11-16 09:32 UTC, merged